// Set Up Interview actions
export const SET_NUM_QUESTIONS = 'SET_NUM_QUESTIONS';
export const CLEAR_NUM_QUESTIONS = 'CLEAR_NUM_QUESTIONS';
export const SET_CATEGORIES = 'SET_CATEGORY';
export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES';
export const REQUEST_QUESTIONSAPI = 'REQUEST_QUESTIONSAPI';
export const SUCCESS_QUESTIONSAPI = 'SUCCESS_QUESTIONSAPI';
